// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYDjtP6JdmJrRuYEBKwXZ1JSgxioldi6E',
    appId: '1:98975695485:web:f7e1e5502c2c44ca08e714',
    messagingSenderId: '98975695485',
    projectId: 'lynq-a91d1',
    authDomain: 'lynq-a91d1.firebaseapp.com',
    storageBucket: 'lynq-a91d1.firebasestorage.app',
    measurementId: 'G-DEYS8RH72L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhajBVtOMYyPgTG2CLPBuFASozt8mZ01I',
    appId: '1:98975695485:android:7913dc65c7f6b9ad08e714',
    messagingSenderId: '98975695485',
    projectId: 'lynq-a91d1',
    storageBucket: 'lynq-a91d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoNP1u9QOd64k34I3vmpC1aYbvN1jD7RY',
    appId: '1:98975695485:ios:08e374776eaa0a4c08e714',
    messagingSenderId: '98975695485',
    projectId: 'lynq-a91d1',
    storageBucket: 'lynq-a91d1.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoNP1u9QOd64k34I3vmpC1aYbvN1jD7RY',
    appId: '1:98975695485:ios:08e374776eaa0a4c08e714',
    messagingSenderId: '98975695485',
    projectId: 'lynq-a91d1',
    storageBucket: 'lynq-a91d1.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYDjtP6JdmJrRuYEBKwXZ1JSgxioldi6E',
    appId: '1:98975695485:web:e83134185a96fc1908e714',
    messagingSenderId: '98975695485',
    projectId: 'lynq-a91d1',
    authDomain: 'lynq-a91d1.firebaseapp.com',
    storageBucket: 'lynq-a91d1.firebasestorage.app',
    measurementId: 'G-HCBGJ625QQ',
  );

}